kind: pipeline
type: docker
name: default

steps:
- name: 前端构建
  image: guoxudongdocker/node-drone
  commands:
    - npm install
    - cd themes/sagiri
    - npm install 
    - cd ../../
    - npm run build
- name: SCP File Transfer
  image: appleboy/drone-scp
  settings:
    target: /data/mywebroot/
    source: ./public
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    command_timeout: 
      from_secret: ssh_timeout
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
- name: Web Deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    script:
      - mv /data/mywebroot/public/* /data/mywebroot/
      - rm -rf /data/mywebroot/public/
trigger:
  event:
  - push
restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache