kind: pipeline
type: docker
name: default

steps:
- name: restore-cache  
  image: drillster/drone-volume-cache  
  settings:  
    restore: true  
    mount:  
      - ./.npm-cache  
      - ./node_modules  
  volumes:  
    - name: cache  
      path: /cache   
- name: 前端主题构建
  image:  node:lts
  commands:
    - cd themes/sagiri
    - npm config set cache ./.npm-cache --global 
    - npm --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/mirrors/node  install  
- name: 前端构建
  image:  node:lts
  commands:
    # - yarn config set registry https://registry.npm.taobao.org/
    # - yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
    - yarn config set proxy http://172.30.240.1:7890
    - yarn config set https-proxy http://172.30.240.1:7890
    - yarn
    - npx  hexo clean
    -  npx  hexo  g
- name: SCP File Transfer
  image: appleboy/drone-scp
  settings:
    target: /data/src/
    source: ./public
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    command_timeout: 
      from_secret: ssh_timeout
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
- name: Web Deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    script:
      - rm -rf  /data/mywebroot/*
      - mv /data/src/public/* /data/mywebroot/
      - rm -rf /data/src/public/
trigger:
  event:
  - push
restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
volumes:  
  - name: cache  
    host:  
      path: /tmp/cache