kind: pipeline
type: docker
name: default

steps:
# - name: themeclone
#   image: alpine/git
#   commands:
#   - git clone -b master http://192.168.50.16:1280/gitea/hexo-theme-sagiri.git themes/sagiri
- name: Hexo Build
  image: node:16.4.2
  commands:
    - yarn config set registry https://registry.npm.taobao.org/
    - npm config set registry https://registry.npm.taobao.org
    - yarn
    - cd themes/sagiri
    - cd ../../
    - yarn
    - hexo g

- name: SCP File Transfer
  image: appleboy/drone-scp
  settings:
    target: /data/mywebroot/
    source: ./public
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    command_timeout: 
      from_secret: ssh_timeout
    # rm: true
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
- name: Web Deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    script:
      - mv /data/mywebroot/public/* /data/mywebroot/
      - rm -rf /data/mywebroot/public/
trigger:
  event:
  - push