kind: pipeline
type: docker
name: default

steps:
- name: restore-cache  
  image: drillster/drone-volume-cache  
  settings:  
    restore: true  
    mount:  
      - ./.npm-cache  
      - ./node_modules  
  volumes:  
    - name: cache  
      path: /cache   
- name: 前端主题构建
  image:  node:lts
  commands:
    - cd themes/sagiri
    - npm config set cache ./.npm-cache --global 
    - npm --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/mirrors/node  install  
- name: 前端构建
  image: node:lts
  commands:
      - npm config set cache ./.npm-cache --global 
      - yarn config set registry https://registry.npm.taobao.org/
      - cp  .downloadrc ~/
      - yarn  install
      - npx hexo cl
      - npx hexo g
- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
- name: SCP File Transfer
  image: appleboy/drone-scp
  settings:
    target: /data/src/
    source: ./public
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    command_timeout: 
      from_secret: ssh_timeout
  when:
    event:
      - tag
- name: Web Deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    port: 
      from_secret: ssh_port
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    script:
      - rm -rf  /home/hxf/nginx-blog/html/*
      - mv /data/src/public/* /home/hxf/nginx-blog/html/
      - rm -rf /data/src/public/
    when:
      event:
          - tag
restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
volumes:  
  - name: cache  
    host:  
      path: /home/hxf/cache
